// Generated by gencpp from file navx_publisher/stampedUInt64.msg
// DO NOT EDIT!


#ifndef NAVX_PUBLISHER_MESSAGE_STAMPEDUINT64_H
#define NAVX_PUBLISHER_MESSAGE_STAMPEDUINT64_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace navx_publisher
{
template <class ContainerAllocator>
struct stampedUInt64_
{
  typedef stampedUInt64_<ContainerAllocator> Type;

  stampedUInt64_()
    : header()
    , data(0)  {
    }
  stampedUInt64_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , data(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint64_t _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::navx_publisher::stampedUInt64_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navx_publisher::stampedUInt64_<ContainerAllocator> const> ConstPtr;

}; // struct stampedUInt64_

typedef ::navx_publisher::stampedUInt64_<std::allocator<void> > stampedUInt64;

typedef boost::shared_ptr< ::navx_publisher::stampedUInt64 > stampedUInt64Ptr;
typedef boost::shared_ptr< ::navx_publisher::stampedUInt64 const> stampedUInt64ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navx_publisher::stampedUInt64_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navx_publisher::stampedUInt64_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace navx_publisher

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'navx_publisher': ['/home/anjasheppard/landing-site-estimation/src/lse_ws/src/navx_publisher/msg', '/home/anjasheppard/landing-site-estimation/src/lse_ws/src/navx_publisher/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navx_publisher::stampedUInt64_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navx_publisher::stampedUInt64_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navx_publisher::stampedUInt64_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d38f591dd58914b3003b137ec2273dd";
  }

  static const char* value(const ::navx_publisher::stampedUInt64_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d38f591dd58914bULL;
  static const uint64_t static_value2 = 0x3003b137ec2273ddULL;
};

template<class ContainerAllocator>
struct DataType< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navx_publisher/stampedUInt64";
  }

  static const char* value(const ::navx_publisher::stampedUInt64_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
uint64 data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::navx_publisher::stampedUInt64_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stampedUInt64_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navx_publisher::stampedUInt64_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navx_publisher::stampedUInt64_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVX_PUBLISHER_MESSAGE_STAMPEDUINT64_H
