// Generated by gencpp from file altimeter_pub/yocto_msg.msg
// DO NOT EDIT!


#ifndef ALTIMETER_PUB_MESSAGE_YOCTO_MSG_H
#define ALTIMETER_PUB_MESSAGE_YOCTO_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <sensor_msgs/Temperature.h>

namespace altimeter_pub
{
template <class ContainerAllocator>
struct yocto_msg_
{
  typedef yocto_msg_<ContainerAllocator> Type;

  yocto_msg_()
    : header()
    , altitude(0.0)
    , pressure(0.0)
    , temperature()  {
    }
  yocto_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , altitude(0.0)
    , pressure(0.0)
    , temperature(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _pressure_type;
  _pressure_type pressure;

   typedef  ::sensor_msgs::Temperature_<ContainerAllocator>  _temperature_type;
  _temperature_type temperature;




  typedef boost::shared_ptr< ::altimeter_pub::yocto_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::altimeter_pub::yocto_msg_<ContainerAllocator> const> ConstPtr;

}; // struct yocto_msg_

typedef ::altimeter_pub::yocto_msg_<std::allocator<void> > yocto_msg;

typedef boost::shared_ptr< ::altimeter_pub::yocto_msg > yocto_msgPtr;
typedef boost::shared_ptr< ::altimeter_pub::yocto_msg const> yocto_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::altimeter_pub::yocto_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::altimeter_pub::yocto_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace altimeter_pub

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'altimeter_pub': ['/home/anjasheppard/landing-site-estimation/src/lse_ws/src/altimeter_pub/msg'], 'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::altimeter_pub::yocto_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::altimeter_pub::yocto_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::altimeter_pub::yocto_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a7b9308cb8964802e3d78385970d78f";
  }

  static const char* value(const ::altimeter_pub::yocto_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a7b9308cb896480ULL;
  static const uint64_t static_value2 = 0x2e3d78385970d78fULL;
};

template<class ContainerAllocator>
struct DataType< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "altimeter_pub/yocto_msg";
  }

  static const char* value(const ::altimeter_pub::yocto_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# raw alt msg\n\
std_msgs/Header header\n\
float64 altitude # m\n\
float64 pressure # hPa\n\
sensor_msgs/Temperature temperature # C\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Temperature\n\
 # Single temperature reading.\n\
\n\
 Header header           # timestamp is the time the temperature was measured\n\
                         # frame_id is the location of the temperature reading\n\
\n\
 float64 temperature     # Measurement of the Temperature in Degrees Celsius\n\
\n\
 float64 variance        # 0 is interpreted as variance unknown\n\
";
  }

  static const char* value(const ::altimeter_pub::yocto_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.altitude);
      stream.next(m.pressure);
      stream.next(m.temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yocto_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::altimeter_pub::yocto_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::altimeter_pub::yocto_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "pressure: ";
    Printer<double>::stream(s, indent + "  ", v.pressure);
    s << indent << "temperature: ";
    s << std::endl;
    Printer< ::sensor_msgs::Temperature_<ContainerAllocator> >::stream(s, indent + "  ", v.temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALTIMETER_PUB_MESSAGE_YOCTO_MSG_H
